# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall

EXTRA_CFLAGS += -Itechpack/audio/include
EXTRA_CFLAGS += -Itechpack/audio/include/uapi

EXTRA_CFLAGS += -DCONFIG_SND_SOC_AOV_TRIGGER

ifeq ($(CONFIG_LIBER_DTB), y)
EXTRA_CFLAGS += -DCONFIG_AW882XX_CODEC -DCONFIG_AW882XX_DSP
snd_smartpa_aw882xx-objs = aw882xx.o
obj-m += snd_smartpa_aw882xx.o
endif

ifeq ($(CONFIG_ODESSA_DTB), y)
EXTRA_CFLAGS += -DCONFIG_AW882XX_CODEC -DCONFIG_AW882XX_DSP
snd_smartpa_aw882xx-objs = aw882xx.o
obj-m += snd_smartpa_aw882xx.o
endif

ifeq ($(CONFIG_BORNR_DTB), y)
EXTRA_CFLAGS += -DCONFIG_TAS2562_REGMAP -DCONFIG_TAS2562_CODEC -DCONFIG_SND_SOC_TAS2562 -DTAS2558_CODEC -DCONFIG_TAS25XX_ALGO -DCONFIG_TAS25XX_CALIB
endif

# debugging support (also enables trace_printk)
EXTRA_CFLAGS += -Isound/soc/codecs/inc
EXTRA_CFLAGS += -Werror

ifeq ($(CONFIG_PARKER_DTB), y)
cirrus_madera-objs = madera.o madera-slimbus.o
obj-m += cirrus_madera.o

cirrus_wm_adsp-objs = wm_adsp.o
obj-m += cirrus_wm_adsp.o

cirrus_cs35l35-objs = cs35l35.o
obj-m += cirrus_cs35l35.o

cirrus_cs35l36-objs = cs35l36.o cs35l36-tables.o
obj-m += cirrus_cs35l36.o

cirrus_cs47l35-objs =  cs47l35.o
obj-m += cirrus_cs47l35.o

cirrus_cs47l90-objs =  cs47l90.o
obj-m += cirrus_cs47l90.o

obj-m += aov_trigger.o

cirrus_cs35l41-objs = cs35l41.o cs35l41-tables.o
obj-m += cirrus_cs35l41.o

ifneq ($(filter m y,$(CONFIG_SND_SOC_CS35L41_SPI)),)
   cirrus_cs35l41-objs += cs35l41-spi.o
else
   cirrus_cs35l41-objs += cs35l41-i2c.o
endif

cirrus_playback-objs = msm-cirrus-playback.o
obj-m += cirrus_playback.o
endif

ifeq ($(CONFIG_UNKNOWN_DTB), y)
tas2562-objs = tas2562-codec.o tas2562-regmap.o tas25xx-algo.o tas25xx-calib.o
obj-m += tas2562.o
endif
